#!/usr/bin/env bash
# install_vps.sh — Set up nginx reverse proxy on your sintaris.net VPS
#
# Run as root on the VPS:
#   bash install_vps.sh
#
# Before running:
#   1. DNS: agents.sintaris.net A record must point to THIS VPS's public IP
#   2. Have the Pi SSH public keys ready (generated by setup_tunnel_key.sh on each Pi)
#
# What this script does:
#   - Installs nginx, certbot
#   - Creates a restricted 'picobridge' tunnel-only user on the VPS
#   - Adds Pi SSH public keys to that user (port-forwarding only, no shell)
#   - Obtains a Let's Encrypt certificate for agents.sintaris.net
#   - Deploys the nginx reverse proxy config
#   - Sets up automatic cert renewal

set -euo pipefail

DOMAIN="${VPS_DOMAIN:-agents.sintaris.net}"
CERTBOT_EMAIL="${CERTBOT_EMAIL:-${1:-}}"    # Set CERTBOT_EMAIL in .env or pass as argument
BRIDGE_USER="${VPS_BRIDGE_USER:-picobridge}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Prerequisites ────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    echo "ERROR: Run as root (sudo bash install_vps.sh your@email.com)" >&2
    exit 1
fi

if [[ -z "$CERTBOT_EMAIL" ]]; then
    read -r -p "Your email for Let's Encrypt notifications: " CERTBOT_EMAIL
fi

if ! host "${DOMAIN}" &>/dev/null; then
    echo "WARNING: ${DOMAIN} doesn't resolve yet."
    echo "  Make sure the A record is set BEFORE obtaining the certificate."
    read -r -p "Continue anyway? [y/N] " yn
    [[ "$yn" =~ ^[Yy]$ ]] || exit 1
fi

# ── [1/6] Install packages ───────────────────────────────────────────────────
echo ""
echo "=== [1/6] Installing nginx, certbot ==="
apt-get update -qq
apt-get install -y nginx certbot python3-certbot-nginx curl

# ── [2/6] Create restricted tunnel user ─────────────────────────────────────
echo ""
echo "=== [2/6] Creating tunnel user: ${BRIDGE_USER} ==="
if ! id "${BRIDGE_USER}" &>/dev/null; then
    useradd -r -s /usr/sbin/nologin -m "${BRIDGE_USER}"
    echo "  User ${BRIDGE_USER} created."
else
    echo "  User ${BRIDGE_USER} already exists — skip."
fi

AUTHKEYS="/home/${BRIDGE_USER}/.ssh/authorized_keys"
mkdir -p "/home/${BRIDGE_USER}/.ssh"
touch "${AUTHKEYS}"
chmod 700 "/home/${BRIDGE_USER}/.ssh"
chmod 600 "${AUTHKEYS}"
chown -R "${BRIDGE_USER}:${BRIDGE_USER}" "/home/${BRIDGE_USER}/.ssh"

# ── [3/6] Add Pi SSH public keys ─────────────────────────────────────────────
echo ""
echo "=== [3/6] Adding Pi public keys ==="
echo ""
echo "Paste the Pi1 (OpenClawPI) public key below."
echo "You got it from running:  bash setup_tunnel_key.sh  on Pi1"
echo "(It looks like: ssh-ed25519 AAAA... pi1-picoassist)"
echo ""
read -r -p "Pi1 public key: " PI1_KEY
if [[ -n "$PI1_KEY" ]]; then
    echo "restrict,port-forwarding ${PI1_KEY}" >> "${AUTHKEYS}"
    echo "  Pi1 key added."
else
    echo "  WARNING: No Pi1 key added. Add manually to ${AUTHKEYS}"
fi

echo ""
echo "Paste the Pi2 (OpenClawPI2) public key (or press Enter to skip):"
read -r -p "Pi2 public key: " PI2_KEY
if [[ -n "$PI2_KEY" ]]; then
    echo "restrict,port-forwarding ${PI2_KEY}" >> "${AUTHKEYS}"
    echo "  Pi2 key added."
else
    echo "  Pi2 key skipped — add manually to ${AUTHKEYS} later."
fi

# ── [4/6] Allow GatewayPorts for loopback tunnels ────────────────────────────
echo ""
echo "=== [4/6] Configuring sshd ==="
SSHD_CONFIG="/etc/ssh/sshd_config"
if ! grep -q "^GatewayPorts" "${SSHD_CONFIG}"; then
    echo "" >> "${SSHD_CONFIG}"
    echo "# Allow reverse tunnel ports on loopback only (for picobridge tunnels)" >> "${SSHD_CONFIG}"
    echo "GatewayPorts no" >> "${SSHD_CONFIG}"
    echo "  GatewayPorts no added (tunnels bind to 127.0.0.1 only — not public)."
fi
systemctl reload sshd || systemctl reload ssh

# ── [5/6] Obtain Let's Encrypt certificate ───────────────────────────────────
echo ""
echo "=== [5/6] Obtaining Let's Encrypt certificate for ${DOMAIN} ==="

# Temporary minimal HTTP server for ACME challenge
mkdir -p /var/www/certbot
cat > /etc/nginx/sites-available/certbot-temp.conf <<'EOF'
server {
    listen 80;
    server_name _;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 200 'cert pending'; add_header Content-Type text/plain; }
}
EOF
ln -sf /etc/nginx/sites-available/certbot-temp.conf /etc/nginx/sites-enabled/certbot-temp.conf
rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true
nginx -t && systemctl reload nginx

certbot certonly \
    --webroot -w /var/www/certbot \
    -d "${DOMAIN}" \
    --email "${CERTBOT_EMAIL}" \
    --agree-tos \
    --non-interactive

rm -f /etc/nginx/sites-enabled/certbot-temp.conf
echo "  Certificate obtained."

# ── [6/6] Deploy nginx config ────────────────────────────────────────────────
echo ""
echo "=== [6/6] Deploying nginx config ==="

# Look for the config file next to this script, or in the current directory
NGINX_CONF=""
for loc in "${SCRIPT_DIR}/nginx-vps.conf" "./nginx-vps.conf"; do
    if [[ -f "$loc" ]]; then
        NGINX_CONF="$loc"
        break
    fi
done

if [[ -z "$NGINX_CONF" ]]; then
    echo "  ERROR: nginx-vps.conf not found next to install_vps.sh"
    echo "  Copy nginx-vps.conf to the same directory and re-run step 6:"
    echo "    cp nginx-vps.conf /etc/nginx/sites-available/agents.sintaris.net"
    echo "    ln -sf /etc/nginx/sites-available/agents.sintaris.net /etc/nginx/sites-enabled/"
    echo "    nginx -t && systemctl reload nginx"
else
    sed "s/__DOMAIN__/${DOMAIN}/g" "${NGINX_CONF}" > "/etc/nginx/sites-available/${DOMAIN}"
    ln -sf "/etc/nginx/sites-available/${DOMAIN}" \
           "/etc/nginx/sites-enabled/${DOMAIN}"
    nginx -t && systemctl reload nginx
    echo "  nginx config deployed and reloaded for ${DOMAIN}."
fi

# Auto-renew cron (if not already set)
if ! crontab -l 2>/dev/null | grep -q "certbot renew"; then
    (crontab -l 2>/dev/null; echo "0 3 * * * certbot renew --quiet && systemctl reload nginx") | crontab -
    echo "  Auto-renewal cron added (daily at 03:00)."
fi

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════════════════════════"
echo " ✅  VPS setup complete!"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Now start the SSH tunnels on the Pis:"
echo ""
echo "  On Pi1 (OpenClawPI):  sudo systemctl enable --now taris-tunnel"
echo "  On Pi2 (OpenClawPI2): sudo systemctl enable --now taris-tunnel"
echo ""
echo "Then test:"
echo "  curl -I https://${DOMAIN}/picoassist/"
echo "  curl -I https://${DOMAIN}/picoassist2/"
echo ""
echo "Expected: HTTP/2 200 (after tunnels connect)"
echo ""
echo "Note: If a Pi is offline, its path returns 502 Bad Gateway — normal."
