# HTTP vhost for certbot challenge only
server {
    listen 80;
    server_name shell.dev2null.de;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
